version: "3.9"
services:
  backend:
    container_name: poligram-inventory-book-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  frontend:
    container_name: poligram-inventory-book-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
