version: "3.9"
services:
  backend:
    container_name: poligram-inventory-book-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  frontend:
    container_name: poligram-inventory-book-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    ports:
      - 8000:8080
      - 50000:50000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
