### Create a new bok
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "id": 19928,
  "name": "Mythical Man-Month, The Essays on Software Engineering",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "author": "Frederick P. Brooks",
  "isbn": "9780201835953",
  "price": 190000,
  "category": "Engineering",
  "publicationYear": 1995
}

### update a book
PUT http://localhost:8080/api/books/19928
Content-Type: application/json

{
  "name": "Mythical Man-Month",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "author": "Frederick P. Brooks",
  "isbn": "9780201835953",
  "price": 190000,
  "category": "Engineering",
  "publicationYear": 1996
}

### get book by id
GET http://localhost:8080/api/books/19928

### get all books
GET http://localhost:8080/api/books